### ISSUE TITLE
Структура и документация.

### ISSUE THREAD

**Issue by bmsdave** [hacad/dronecafe#3]
1. Перейти на npm 5.*.*
2. Добавить package-lock.json (кстати, зачем он нужен?)
3. Используя синтаксис jsdoc описать основные методы как client-side, так и server-side. Если есть желание, можно посмотреть в сторону angular-jsdoc.

+ По поводу структуры проекта:
Приветствуется когда в одном каталоге находится код связанный с одной сущностью. Т.е. разделять не на models/routes а на order/client/dish и т.д. в плоть до того что и тесты и клиентская часть(вкоючая html/css) и серверная часть связанная с, например, client находится в одном месте.

**Comment by hacad** [comment]
fixed
